// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyRUHgpTGsQBImS6rGq_fl6z0pxEve8nI',
    appId: '1:105504636787:web:23c290179a9076c4664f06',
    messagingSenderId: '105504636787',
    projectId: 'sdlab-6934e',
    authDomain: 'sdlab-6934e.firebaseapp.com',
    storageBucket: 'sdlab-6934e.appspot.com',
    measurementId: 'G-FLEY6XZHZC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrNVkk9-Ptqpdfkpo2S843SWRXsOC8aZk',
    appId: '1:105504636787:android:75fd15baa04c041b664f06',
    messagingSenderId: '105504636787',
    projectId: 'sdlab-6934e',
    storageBucket: 'sdlab-6934e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnddl6MwQ-_3tCdqYRWkKj6DHk2flbI68',
    appId: '1:105504636787:ios:cba9d3a56ca89e28664f06',
    messagingSenderId: '105504636787',
    projectId: 'sdlab-6934e',
    storageBucket: 'sdlab-6934e.appspot.com',
    iosClientId: '105504636787-jnoia6p9qilre3m91h3c5fivvs20qufa.apps.googleusercontent.com',
    iosBundleId: 'com.example.barcodeDetector',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDnddl6MwQ-_3tCdqYRWkKj6DHk2flbI68',
    appId: '1:105504636787:ios:cba9d3a56ca89e28664f06',
    messagingSenderId: '105504636787',
    projectId: 'sdlab-6934e',
    storageBucket: 'sdlab-6934e.appspot.com',
    iosClientId: '105504636787-jnoia6p9qilre3m91h3c5fivvs20qufa.apps.googleusercontent.com',
    iosBundleId: 'com.example.barcodeDetector',
  );
}
